baseURL       = "https://yashparna.netlify.app"
languageCode  = "en-us"
title         = "Yashparna De"
theme = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "About"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  [[menu.nav]]
    name    = "Blog"
    url     = "blog"
    weight  = 4
  [[menu.nav]]
    name    = "Get in touch"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/logo.png"
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  formspreeFormUrl  = "https://formspree.io/xzbjqlpn"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/hero-background.jpg"
    heading               = "Hello,this is Yashparna"
    tagline               = "Electronics Engineer student,Aspiring data scientist"
    primary_button        = "See my Works"
    primary_button_url    = "portfolio"
    secondary_button      = "Connect with me"
    secondary_button_url  = "contact"

  [params.portfolio]
    enable    = true
    title     = "PORTFOLIO and RECENT WORKS"
    subtitle  = "Crafting experiences and seeking to make the complex clear & beautiful."

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "QUESTIONS?"
    primary_button      = "Submit Query"
    primary_button_url  = "contact"
    secondary_button    = "Go through works again"
    secondary_button_url = "portfolio"

  [params.footer]
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contact Info:"
      address   = "yashparnade@gmail.com"
      email   = "yashparnade.ec18@rvce.edu.in"
      # Footer Sitemap
      [params.footer.sitemap]
        title   = "Sitemap"
        [[params.footer.sitemap.link]]
          name = "About me"
          url  = "about"
        [[params.footer.sitemap.link]]
          name = "Projects"
          url  = "portfolio"
        [[params.footer.sitemap.link]]
          name = "Blog"
          url  = "blog"
        [[params.footer.sitemap.link]]
          name = "Contact"
          url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Social Media"
        [[params.footer.social.link]]
          name = "Linkdin"
          url  = "https://www.linkedin.com/in/yashparna-de-a9770517a"
        [[params.footer.social.link]]
          name = "FaceBook"
          url  = "https://www.facebook.com/yashparnade"

      # Footer Service
      [params.footer.service]
        title       = "Education"
        description = "X (CBSE): Delhi Public School, Madhya Pradesh<br>XII (CBSE): Holy Garden Modern School, West Bengal <br>B Tech in Electronics & Communications Engg.: <br>R.V. College of Engineering, Banglore"
